name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.5.1
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3
  flutter_apns_only: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter