name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.5.3
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  flutter_apns_only: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
