name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.5.4
homepage: https://github.com/mwaylabs/flutter-apns

plugin:
  platforms:
    android:
      pluginClass: FirebasePushConnector
    ios:
      pluginClass: ApnsPushConnector

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_apns_only: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
