name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.5.1
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  flutter_apns_only: ^1.5.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter