name: flutter_apns_example
description: Demonstrates how to use the flutter_apns plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependency_overrides:
  plugin_platform_interface: ^2.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^1.3.0

  flutter_local_notifications: ^4.0.1+2
  flutter_apns:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true