name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.1.0
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.mwaysolutions.flutter.apns
    pluginClass: FlutterApnsPlugin

