name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.3.1
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^7.0.0
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mwaysolutions.flutter.apns
        pluginClass: FlutterApnsPlugin
      ios:
        pluginClass: FlutterApnsPlugin